/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "24px",
      screens: {
        "mobile": "640px",
        "tablet": "768px",
        "desktop": "1024px",
        "large": "1200px",
      },
    },
    extend: {
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'inter': ['Inter', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'Monaco', 'Consolas', 'monospace'],
        'jetbrains': ['JetBrains Mono', 'Monaco', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        'green-accent': "hsl(var(--green-accent))",
        'blue-accent': "hsl(var(--blue-accent))",
        'purple-accent': "hsl(var(--purple-accent))",
        'orange-accent': "hsl(var(--orange-accent))",
        'cursor-purple': '#8B5CF6',
        'cursor-blue': '#3B82F6',
        'cursor-green': '#10B981',
        'cursor-orange': '#F59E0B',
        'cursor-pink': '#EC4899',
        'neutral-black': '#000000',
        'neutral-gray-900': '#111827',
        'neutral-gray-800': '#1F2937',
        'neutral-gray-700': '#374151',
        'neutral-gray-600': '#4B5563',
        'neutral-gray-500': '#6B7280',
        'neutral-gray-400': '#9CA3AF',
        'neutral-gray-300': '#D1D5DB',
        'neutral-gray-200': '#E5E7EB',
        'neutral-gray-100': '#F3F4F6',
        'neutral-white': '#FFFFFF',
        'white-10': 'rgba(255, 255, 255, 0.1)',
        'white-20': 'rgba(255, 255, 255, 0.2)',
        'white-30': 'rgba(255, 255, 255, 0.3)',
        'black-10': 'rgba(0, 0, 0, 0.1)',
        'black-20': 'rgba(0, 0, 0, 0.2)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        'sm': '6px',
        'md': '8px', 
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        'full': '9999px',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(40px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        hover: {
          '0%': { transform: 'translateY(0px)' },
          '100%': { transform: 'translateY(-2px)' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        'fade-in': 'fadeIn 0.6s ease-out',
        'slide-up': 'slideUp 0.6s ease-out',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0.0, 0.6, 1) infinite',
        'hover': 'hover 0.3s cubic-bezier(0.4, 0.0, 0.2, 1)',
      },
      fontSize: {
        'hero': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h2': ['36px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'caption': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        '3xl': '64px',
        '4xl': '96px',
      },
      boxShadow: {
        'sm': '0 2px 4px rgba(0, 0, 0, 0.1)',
        'md': '0 4px 12px rgba(0, 0, 0, 0.15)',
        'lg': '0 8px 32px rgba(0, 0, 0, 0.2)',
        'xl': '0 12px 40px rgba(0, 0, 0, 0.3)',
        'glow': '0 0 20px rgba(139, 92, 246, 0.3)',
        'glass-sm': '0 8px 32px rgba(0, 0, 0, 0.2)',
        'glass-lg': '0 12px 40px rgba(0, 0, 0, 0.3)',
        'button-primary': '0 4px 12px rgba(139, 92, 246, 0.3)',
        'button-primary-hover': '0 6px 16px rgba(139, 92, 246, 0.4)',
      },
      backgroundImage: {
        'hero-gradient': 'radial-gradient(ellipse at center, rgba(139, 92, 246, 0.1) 0%, transparent 60%)',
        'button-primary': 'linear-gradient(135deg, #8B5CF6 0%, #6366F1 100%)',
        'button-primary-hover': 'linear-gradient(135deg, #7C3AED 0%, #5B21B6 100%)',
        'button-green': 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
        'button-blue': 'linear-gradient(135deg, #3B82F6 0%, #2563EB 100%)',
        'card-gradient': 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 50%, #F59E0B 100%)',
        'icon-gradient': 'linear-gradient(45deg, #10B981 0%, #3B82F6 100%)',
        'text-gradient-primary': 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)',
        'text-gradient-green': 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
        'text-gradient-blue': 'linear-gradient(135deg, #3B82F6 0%, #2563EB 100%)',
      },
      backdropBlur: {
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
      },
      screens: {
        'mobile': '640px',
        'tablet': '768px',
        'desktop': '1024px',
        'large': '1280px',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0.0, 0.2, 1)',
      },
    },
  },
  plugins: [],
} 